### ISSUE TITLE
ImportError: cannot import name 'ParaClient' from 'paraclient'

### ISSUE THREAD

**Issue by SHogenboom** [Erudika/para-client-python#3]
Sorry if this is an obvious question - I’m relatively new to using Python! 

I’ve created a virtual environment and installed the paraclient:
```
# Create new virtual environment
python3.10 -m venv env
# Activate the virtual environment
source env/bin/activate
# Install the para client for python
python3.10 -m pip install paraclient
# update?
# pip install paraclient --upgrade
# Store in requirements file (for reproducibility)
python3.10 -m pip freeze > python_requirements.txt
```

I then try to run the code from the `readme` example:
```
from paraclient import ParaClient
```

but get the error `ImportError: cannot import name 'ParaClient' from ‘paraclient’`. The reference points to the library (which was installed) to the `init.py` file - which is empty. Online I can only find suggestions that this is caused by a circular reference import. Looking at the code though I do not see if/where this would be the case.

Hope you can help!

**Comment by albogdano** [comment]
Fixed, I think. Also, you will need to add `aws-requests-auth` and `requests` to your requirements.txt:
https://github.com/Erudika/para-client-python/blob/master/requirements.txt

**Comment by albogdano** [comment]
Also, please update to version `1.36.8` which is now published on PyPI.

**Comment by SHogenboom** [comment]
Thanks! It works 👍🏽
